[package]
name = "option_pricer"
version = "0.1.0"
authors = ["ronnie chowdhury <ronnie.c995@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray={ version="0.13", features=["rayon","approx"] }