# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  mssolution: '**/aarcserviceshosted.sln'
  etlsolution: '**/aarcETL.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  displayName: 'Restore nuget packages'
  inputs:
    restoreSolution: '$(mssolution)'
    restoreSolution: '$(etlsolution)'
    
- task: VSBuild@1
  displayName: 'Build Mesh windows ms services'
  inputs:
    solution: '$(mssolution)'
    msbuildArgs: '/p:DeployOnBuild=false /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\MSApp.zip" /p:DeployIisAppPath="Mesh Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSBuild@2
  displayName: 'Build Mesh windows etl services'
  inputs:
    solution: '$(etlsolution)'
    msbuildArgs: '/p:DeployOnBuild=false /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\ETLApp.zip" /p:DeployIisAppPath="ETL Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: DotNetCoreCLI@3
  displayName: 'Run Mesh Framework Tests'
  inputs:
    command: test
    projects: '**/UT/*/AARC.MeshTests.csproj'
    arguments: '--configuration $(buildConfiguration)'
