# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-18.04'

variables:
  net_lib_path: $(Build.SourcesDirectory)/Rust/net_lib
  rust_release_path: $(Build.SourcesDirectory)/Rust/net_lib/target/release
  imageName: test-rust-repo

steps:
  - script: |
      curl https://sh.rustup.rs -sSf | sh -s -- -y
      echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
    displayName: Install Build Mesh Core (Rust)
  - script: cargo build --release
    workingDirectory: '$(net_lib_path)'
  - task: CopyFiles@2
    inputs:
      Contents: $(net_lib_path)/Channel.toml
      TargetFolder: $(rust_release_path)
  - publish: $(rust_release_path)
    artifact: Rust
    displayName: artifact '$(rust_release_path)'